**KUIS 2**

Nama  : Diajeng Nidzom Yoesharnilillah

Kelas : TI-3B

Absen : 11

Soal

1. Lakukan pemilahan data training dan testing yang sesuai dan proposional dari data tersebut!(10 poin)

2. Tentukan data validasi!(10 poin)

3. Tentukan secara tepat kolom yang menjadi "label" (20 poin)

4. Terapkan dua jenis metode klasifikasi dan lakukan perbandingan akurasi  dengan wajib melibatkan variabel keterlibatan volunteer sampai variabel luaran-luaran yang dihasilkan! (20 poin)

5. Lakukan tunning hyperparameter berdasarkan hasil klasifikasi pada nomor 3 menggunakan metode Grid Search dan Random Search! Simpulkan parameter apa yang paling baik digunakan berdasarkan metode klasifikasi yang dipilih, dan berapa akurasinya. (40 poin)

In [ ]:
import pandas as pd

df = pd.read_excel('data/dataset_quiz.xlsx')

df.head(100)

,id_ketua,id_anggota1,id_anggota2,id_anggota3,id_anggota4,id_anggota5,keterlibatan_vltr,jml_vltr_terlibat,tahun,skema,luaran_hki,jenis_luaran_hki,potensi_hki,luaran_lain,jenis_luaran_lain,status_luaran_lain
0,7206.0,7214.0,6211.0,8602.0,7801.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
1,7214.0,7109.0,8402.0,7903.0,9202.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
2,5911.0,8201.0,8701.0,9101.0,9003.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
3,8402.0,7702.0,8602.0,8903.0,8903.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
4,8201.0,8305.0,5911.0,5903.0,8402.0,NaN,TIDAK,0,2019,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,8803.0,8804.0,9102.0,8005.0,9303.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
81,6211.0,8901.0,9003.0,9303.0,9007.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
82,8601.0,8903.0,8703.0,NaN,NaN,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
83,8703.0,8601.0,9202.0,9102.0,6204.0,NaN,YA,3,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA
84,8102.0,7109.0,5903.0,7206.0,8903.0,NaN,TIDAK,0,2022,REGULER,TIDAK ADA,TIDAK ADA,TIDAK,TIDAK ADA,TIDAK ADA,TIDAK ADA

1. Lakukan pemilahan data training dan testing yang sesuai dan proposional dari data tersebut!

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

df['keterlibatan_vltr'] = LE.fit_transform(df['keterlibatan_vltr'])
df['jml_vltr_terlibat'] = LE.fit_transform(df['jml_vltr_terlibat'])
df['skema'] = LE.fit_transform(df['skema'])
df['luaran_hki'] = LE.fit_transform(df['luaran_hki'])
df['jenis_luaran_hki'] = LE.fit_transform(df['jenis_luaran_hki'])
df['potensi_hki'] = LE.fit_transform(df['potensi_hki'])
df['luaran_lain'] = LE.fit_transform(df['luaran_lain'])
df['jenis_luaran_lain'] = LE.fit_transform(df['jenis_luaran_lain'])
df['status_luaran_lain'] = LE.fit_transform(df['status_luaran_lain'])

# drop kolom keterlibatan_vltr
X = df.drop(['keterlibatan_vltr'], axis = 1)
y = df['keterlibatan_vltr']

X = pd.get_dummies(X)

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

from sklearn.preprocessing import MinMaxScaler

# Normalisasi data
scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

2. Tentukan data validasi!

In [ ]:
# Implementasi k-fold cross validation stratified
from sklearn.model_selection import train_test_split, StratifiedKFold

# Split train test
df_train2, df_test2 = train_test_split(df, test_size=0.2, random_state=0)

# Inisiasi obyek StratifiedKFold
skf2 = StratifiedKFold(n_splits=4)
print(f'Jumlah fold: {skf2.get_n_splits()}')
print(f'Obyek SKFold: {skf2}')

# Melakukan split train menjadi train dan validasi
skf2_split = skf2.split(df_train2, df_train2['keterlibatan_vltr'])
print(f'Jumlah data df: {len(df_train2)}')

# Mengecek data tiap fold
for train_index, test_index in skf2_split:
    print(f'Index train: {train_index} | Index test:{test_index}')

Jumlah fold: 4
Obyek SKFold: StratifiedKFold(n_splits=4, random_state=None, shuffle=False)
Jumlah data df: 68
Index train: [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67] | Index test:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Index train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 31 32 33 35 36 37 39
 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67] | Index test:[17 18 19 20 21 22 23 24 25 26 27 28 29 30 34 38 40]
Index train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 34 38 40 50 52 53 54 55 56 57 58 59 60 61 62 63 64
 65 66 67] | Index test:[31 32 33 35 36 37 39 41 42 43 44 45 46 47 48 49 51]
Index train: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 51] | Index test:[50 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67]

In [ ]:
df.head()

,id_ketua,id_anggota1,id_anggota2,id_anggota3,id_anggota4,id_anggota5,keterlibatan_vltr,jml_vltr_terlibat,tahun,skema,luaran_hki,jenis_luaran_hki,potensi_hki,luaran_lain,jenis_luaran_lain,status_luaran_lain
0,7206.0,7214.0,6211.0,8602.0,7801.0,NaN,0,0,2019,1,1,1,2,0,3,1
1,7214.0,7109.0,8402.0,7903.0,9202.0,NaN,0,0,2019,1,1,1,2,0,3,1
2,5911.0,8201.0,8701.0,9101.0,9003.0,NaN,0,0,2019,1,1,1,2,0,3,1
3,8402.0,7702.0,8602.0,8903.0,8903.0,NaN,0,0,2019,1,1,1,2,0,3,1
4,8201.0,8305.0,5911.0,5903.0,8402.0,NaN,0,0,2019,1,1,1,2,0,3,1

3. Tentukan secara tepat kolom yang menjadi "label"

In [ ]:
#selanjutnya adalah mengimport variabel untuk label encoder
from sklearn import preprocessing

#lalu menggunakan lable encoder fungsinya agar bisa mengetahui kata 'label'
label_encoder = preprocessing.LabelEncoder()

#lalu menggunakan encode pada label yang ada didalam kolom 'keterlibatan_vltr' 
df['keterlibatan_vltr']= label_encoder.fit_transform(df['keterlibatan_vltr'])
df['jenis_luaran_hki']= label_encoder.fit_transform(df['jenis_luaran_hki'])
df['potensi_hki']= label_encoder.fit_transform(df['potensi_hki'])
df['skema']= label_encoder.fit_transform(df['skema'])
df['luaran_hki']= label_encoder.fit_transform(df['luaran_hki'])
df['luaran_lain']= label_encoder.fit_transform(df['luaran_lain'])
df['jenis_luaran_lain']= label_encoder.fit_transform(df['jenis_luaran_lain'])
df['status_luaran_lain']= label_encoder.fit_transform(df['status_luaran_lain'])

4. Terapkan dua jenis metode klasifikasi dan lakukan perbandingan akurasi dengan wajib melibatkan variabel keterlibatan volunteer sampai variabel luaran-luaran yang dihasilkan!

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC # "Support vector classifier"
from sklearn.metrics import accuracy_score

# DT ENTROPY
dt_entropy = DecisionTreeClassifier(criterion='entropy')

# Fit Model
dt_entropy.fit(X_train, y_train)

# Memprediksi label set test
y_pred_entropy = dt_entropy.predict(X_test)

# Evaluasi
acc_entropy = accuracy_score(y_test, y_pred_entropy)

print(f'Akurasi DT Entropy: {acc_entropy}')

# RANDOM FOREST
svc =  SVC(kernel="linear", C=10, probability=True)

# Fit Model
svc.fit(X_train, y_train)

# Memprediksi label set test
y_pred_svc = svc.predict(X_test)

# Evaluasi
acc_svc = accuracy_score(y_test, y_pred_svc)
print(f'Akurasi SVC: {acc_svc}')

ValueError: ignored

5. Lakukan tunning hyperparameter berdasarkan hasil klasifikasi pada nomor 3 menggunakan metode Grid Search dan Random Search! Simpulkan parameter apa yang paling baik digunakan berdasarkan metode klasifikasi yang dipilih, dan berapa akurasinya.

In [16]:
# GridSearch menggunakan Decission Tree
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold

#inisiasi repeated k-fold
cv = RepeatedKFold(n_splits=4, n_repeats=3, random_state=42)

# Definisikan hyperparameter yang akan digunakan
params = {
    'criterion' : ['gini', 'entropy', 'log_loss'],
    'max_depth' : list(range(5,11))
}

# inisiasi grid berdasarkan nilai repeated k-fold dan hyperparameter
grid = GridSearchCV(clf_tree, param_grid=params, cv=cv)

# Fit / latih berdasarkan grid
%timeit grid.fit(X,y)

# Evaluasi dengan score
score = grid.score(X,y)

print(f'Hasil evaluasi: {score}')
print(f'Konfigurasi hyperparameter : {grid.best_params_}')

NameError: ignored

In [17]:
# Random search menggunakan Decission Tree
from sklearn.model_selection import RandomizedSearchCV

# Definisikan hyperparameter yang akan digunakan
params = {
    'criterion' : ['gini', 'entropy'],
    'max_depth' : list(range(5,11))
}

# inisiasi grid berdasarkan nilai repeated k-fold dan hyperparameter
random = RandomizedSearchCV(clf_tree, params, cv=cv)

# Fit / latih berdasarkan random
%timeit random.fit(X,y)

# Evaluasi dengan score
score = random.score(X,y)

print(f'Hasil evaluasi: {score}')
print(f'Konfigurasi hyperparameter : {random.best_params_}')

NameError: ignored

In [18]:
# Exhausive Search menggunakan Decission Tree
model_dt_manual = DecisionTreeClassifier(criterion='entropy', max_depth=8, max_leaf_nodes=10)

%timeit model_dt_manual.fit(X, y)

# Evaluasi dengan score
score = model_dt_manual.score(X,y)

print(f'Hasil evaluasi: {score}')

ValueError: ignored